---
- hosts: all
  tasks:
    - name: ensure my locale is present
      become: yes
      locale_gen: name=en_US.UTF-8 state=present

    - name: install system packages
      become: yes
      # Updates cache if last update was more than 3 minutes prior (once per run or so)
      apt: name={{ item }} cache_valid_time=180 update_cache=yes
      with_items:
        # (dependencies, should already be installed)
        - ansible
        - git
        - make

        # Basic env
        - tmux
        - zsh
        - vim-gtk
        - python3
        - golang
        - ruby-dev
        - nodejs-legacy

        # Dotfiles dependency
        - stow

        # Tools
        - curl
        - tree
        - xsel

        # Font
        - fonts-hack-ttf

    - name: make bash the default shell
      become: yes
      user: name={{ ansible_user_id }} shell=/bin/bash

    - name: clean up ~
      file: path={{ item }} state=absent
      with_items:
        - ~/.bash_profile
        - ~/.bash_logout
        - ~/.bashrc
        - ~/.zshrc
        - ~/.profile

    - name: pull repo elmisback/dotfiles (dotfiles)
      git: repo=git@github.com:elmisback/dotfiles dest=~/dotfiles accept_hostkey=yes update=no

    - name: get fasd
      get_url: url=https://raw.githubusercontent.com/clvv/fasd/master/fasd dest=~/.local/bin/fasd

    - name: tmux plugins (tmux-plugins/tpm)
      git: repo=git@github.com:tmux-plugins/tpm dest=~/.local/share/tmux/plugins/tpm accept_hostkey=yes update=no

      # TODO fix these
      #- name: install configuration
      #- command: make install chdir=~/dotfiles creates=~/.zshenv

    - name: install Google drive tool (drive)
      command: go get -u github.com/odeke-em/drive/cmd/drive

    - name: Creates directory
      file: path={{ item }} state=directory
      with_items:
        - ~/.config/octave
