---
# TODO uncomment most of these for a full installation
- hosts: all
  tasks:
    #- name: add Debian experimental to /etc/atp/sources.list (neovim)
    #  sudo: yes
    #  apt_repository: repo='deb http://ftp.debian.org/debian experimental main' update_cache=yes

    - name: install system packages
      sudo: yes
      apt: name={{ item }}
      with_items:
        - git
        - zsh
        - tree
        #- xsel  # clipboard support
        #- stow
        #- neovim
        #- python

    #- name: install python packages
    #  pip: name={{ item }}
    #  with_items: python_packages
        #- ipython
        #- tldr.py  # tldr client

    - name: make zsh the default shell
      sudo: yes
      user: name="{{ ansible_user_id }}" shell=/usr/bin/zsh

    #- name: clean up ~
    #  file: path={{ item }} state=absent
    #  with_items:
    #    - ~/.bash_profile
    #    - ~/.bash_logout
    #    - ~/.bashrc
    #    - ~/.profile

    ## TODO modify dest
    #- name: pull repo elmisback/dotfiles
    #  git: repo=git@github.com:elmisback/dotfiles dest=~/dotfiles accept_hostkey=yes

    #- name: install configuration
    #  command: /usr/bin/zsh install.zsh chdir=~/dotfiles creates=~/.zshenv

    #- name: clone fasd
    #  git: repo=https://github.com/clvv/fasd.git dest=/home/vagrant/lib/fasd

    #- name: build fasd
    #  sudo: yes
    #  command: make install chdir=/home/vagrant/lib/fasd creates=/usr/local/bin/fasd
