---
# TODO uncomment most of these for a full installation
- hosts: all
  tasks:
    - name: ensure my locale is present
    - locale_gen: name=en_US.UTF-8 state=present

    - name: install system packages
      become: yes
      apt: name={{ item }}
      with_items:
        # (dependencies)
        - ansible
        - git
        - make

        # Basic env
        - tmux
        - zsh
        - vim-gtk
        - python
        - python-pip

        # Dotfiles dependency
        - stow

        # Tools
        - curl
        - tree
        - xsel

    - name: install python packages
      pip: name={{ item }} state=present
      with_items:
        - ipython

    - name: make zsh the default shell
      become: yes
      user: name="{{ ansible_user_id }}" shell=/usr/bin/zsh

    - name: clean up ~
      file: path={{ item }} state=absent
      with_items:
        - ~/.bash_profile
        - ~/.bash_logout
        - ~/.bashrc
        - ~/.profile

    - name: pull repo elmisback/dotfiles (dotfiles)
      git: repo=git@github.com:elmisback/dotfiles dest=~/dotfiles accept_hostkey=yes update=no

    - name: pull repo elmisback/st (stterm)
      git: repo=git@github.com:elmisback/st dest=~/build/st accept_hostkey=yes update=no

    - name: get fasd
      get_url: url=https://raw.githubusercontent.com/clvv/fasd/master/fasd dest=~/.local/bin/fasd

    - name: tmux plugins (tmux-plugins/tpm)
      git: repo=git@github.com:tmux-plugins/tpm dest=~/.cache/tmux/plugins/tpm accept_hostkey=yes update=no

    - name: install configuration
      command: make install chdir=~/dotfiles creates=~/.zshenv
